version: '3.5'  # Use the latest Docker Compose format

services:
  interface:
    image: interface:latest  # Build the image from the Dockerfile in the current directory
    ports:
      - "8081:8081"  # Map port 8080 of the container to port 8080 on the host
    networks:
      - application
networks:
  application:
    external: true